// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uizuwvnatwmqbvcapmwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpenV3dm5hdHdtcWJ2Y2FwbXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTE2MzAsImV4cCI6MjA3MTI2NzYzMH0.7gxgu77QehniFRX5z_X5oWO-VSH8p9jiPOfRGUwBqiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});